trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: ./build.sh test-one skipdocs
    displayName: build and unit test
  - task: PublishTestResults@2
    inputs:
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
        testRunTitle: Linux Unit Tests

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: build.bat canary skipdocs
    displayName: build and unit test
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
      testRunTitle: Windows Unit Tests
    
